name: Cowsay workflow
on: push

jobs:
  ascii-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Install cowsay
      run: sudo apt-get install -y cowsay
           
    - name: Execute cowsay command
      run: cowsay -f dragon "Run for cover I'm a DRAGON....RAWR!" >> dragon.txt

    - name: Test file exists
      run: grep -i "DRAGON" dragon.txt

    - name: Read the file
      run: cat dragon.txt

    - name: List repo files
      run: ls -ltra

