name: first workflow
on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v7    
        - name: Welcome
          run: echo "First GA Job"

        - name: List files
          run: ls

        - name: read file
          run: cat README.md
