name: first workflow
on: workflow_dispatch

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v7

        - name: Multiple commands
          run: |
            echo "First GA Job"
            ls -ltra
            cat README.md

       

